version: '3.3'
services:
    api:
        hostname: smart-house-api
        container_name: smart_house_api
        environment:
            - PORT=5000
            - MQTT_PORT=1883
            - DB_URL=10.5.0.4
            - DB_NAME=SmartHouse
            - DB_USER=postgres
            - DB_PASSWORD=securePassword
            - DB_PORT=5432
            - MQTT_URL=10.5.0.3
        ports:
            - '9000:5000'
        restart: always
        image: smart_house_server:latest
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2

    mqtt:
        hostname: smart-house-mqtt
        container_name: smart_house_mqtt
        ports:
            - '9001:1883'
        restart: always
        image: smart_house_mqtt:latest
        networks:
            vpcbr:
                ipv4_address: 10.5.0.3
    db:
        hostname: smart-house-db
        image: postgres
        restart: always
        ports:
            - '9002:5432'
        environment:
            POSTGRES_PASSWORD: 'securePassword'
            PGPASSWORD: 'securePassword'
        volumes:
            - ./smarthouse/db:/var/lib/postgresql/data
        networks:
            vpcbr:
                ipv4_address: 10.5.0.4

    adminer:
        hostname: smart-house-adminer
        image: adminer
        restart: always
        ports:
            - 9010:8080
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
