include: package:flutter_lints/flutter.yaml

# https://github.com/dart-lang/lints/blob/main/lib/core.yaml
# https://github.com/dart-lang/lints/blob/main/lib/recommended.yaml
# https://github.com/flutter/packages/blob/main/packages/flutter_lints/lib/flutter.yaml

analyzer:
  exclude:
    - 'bricks/**'
    - 'build/**'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/**/*.config.dart
    - test/**/*.config.dart
    - lib/*.config.dart
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.gr.dart
    - lib/**/*.config.dart
    - lib/models
    - lib/internal_models
    - lib/generated/**

  errors:
    invalid_annotation_target: ignore
    avoid_empty_else: warning
    avoid_print: info
    avoid_returning_null_for_future: warning
    avoid_types_as_parameter_names: warning
    close_sinks: warning
    cancel_subscriptions: warning
    empty_statements: warning
    iterable_contains_unrelated_type: error
    no_duplicate_case_values: warning
    prefer_void_to_null: warning
    throw_in_finally: error
    unnecessary_statements: warning
    unrelated_type_equality_checks: error
    unsafe_html: error
    use_key_in_widget_constructors: warning
    valid_regexps: error
    always_declare_return_types: error
    annotate_overrides: warning
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_double_and_int_checks: warning
    avoid_field_initializers_in_const_classes: warning
    avoid_init_to_null: warning
    avoid_null_checks_in_equality_operators: warning
    avoid_returning_null: warning
    avoid_single_cascade_in_expression_statements: warning
    avoid_types_on_closure_parameters: warning
    await_only_futures: warning
    avoid_void_async: error
    camel_case_types: warning
    constant_identifier_names: warning
    directives_ordering: warning
    library_prefixes: warning
    non_constant_identifier_names: warning
    parameter_assignments: error
    prefer_adjacent_string_concatenation: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_collection_literals: error
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_null_aware_operators: warning
    prefer_single_quotes: warning
    unnecessary_new: error
    use_function_type_syntax_for_parameters: warning
    unawaited_futures: warning
    lines_longer_than_80_chars: info
    type_init_formals: warning
    unnecessary_parenthesis: info
    avoid_relative_lib_imports: warning
    cascade_invocations: info
    always_use_package_imports: warning

linter:
  rules:
    unnecessary_parenthesis: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    # await for async methods in rare case that's not wanted wrap call in unawaited(asyncMethod())
    unawaited_futures: true
    type_init_formals: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    close_sinks: true
    directives_ordering: true
    package_api_docs: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: true
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    prefer_adjacent_string_concatenation: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    valid_regexps: true
    always_declare_return_types: true
    #    always_put_required_named_parameters_first: false
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_single_cascade_in_expression_statements: true
    use_function_type_syntax_for_parameters: true
    avoid_empty_else: true
    empty_statements: true
    camel_case_types: true
    library_prefixes: true
    prefer_null_aware_operators: true
    unnecessary_new: true
    cascade_invocations: true
